# Generated by Django 5.2.7 on 2025-10-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
