# Generated by Django 5.2.7 on 2025-10-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_student_id_customuser_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
