# Generated by Django 5.2.7 on 2025-10-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('senior_high', 'Senior High'), ('university_college', 'University/College')], max_length=20, null=True),
        ),
    ]
