# Generated by Django 5.2.7 on 2025-10-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_senior', 'High/Senior High'), ('university_college', 'University/College')], max_length=20, null=True),
        ),
    ]
